<Project>
	<PropertyGroup>
		<!-- Set this to where ever your ULTRAKILL folder is. -->
		<ULTRAKILLPath>/home/creature/.steam/steam/steamapps/common/ULTRAKILL/</ULTRAKILLPath>

		<!-- You shouldn't need to touch these. If you do, ask me about it on discord @fredayddd321ewq -->
		<ManagedPath>$(ULTRAKILLPath)\ULTRAKILL_Data\Managed</ManagedPath>
		<BepInExPath>$(ULTRAKILLPath)\BepInEx</BepInExPath>
		<CorePath>$(BepInExPath)\core</CorePath>
		<PluginPath>$(BepInExPath)\plugins</PluginPath>
		
		<!-- This is the path where the DLL is copied too, if you have it in a folder or something then add the name of that folder onto here. -->
		<!-- Fuck you die im using my own build script  ! ! ! !  !  -->
		<CopyPath>$(PluginPath)\UltraEditor</CopyPath>
	</PropertyGroup>
</Project>