<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="Paths.props" />

	<PropertyGroup>
		<TargetFramework>netstandard2.1</TargetFramework>
		<AssemblyName>UltraEditor</AssemblyName>
		<Description>WIP in-game level editor for ultrakill</Description>
		<Version>0.1.0</Version>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<LangVersion>latest</LangVersion>
		<NoWarn>CS0649, CS0414</NoWarn>
		<DebugType>embedded</DebugType>

		<!-- Resources so nuget can fucking find BepInEx and Unity. -->
		<RestoreAdditionalProjectSources>
			https://api.nuget.org/v3/index.json;
			https://nuget.bepinex.dev/v3/index.json
		</RestoreAdditionalProjectSources>
	</PropertyGroup>

    <!-- This constant makes the editor be on "Screenshot" mode -->
    <!-- <PropertyGroup>
      <DefineConstants>EXPORTMODE</DefineConstants>
    </PropertyGroup> -->

	<ItemGroup Condition="'$(TargetFramework.TrimEnd(`0123456789`))' == 'net'">
		<PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.2" PrivateAssets="all" />
	</ItemGroup>
	
	<ItemGroup>
		<!-- Embed the assetbundles into the dll. -->
		<EmbeddedResource Include="Assets\emptyscene.bundle" />
		<EmbeddedResource Include="Assets\editorcanvas.bundle" />
		<EmbeddedResource Include="Assets\sample.bundle" />

		<!-- Packages -->
		<PackageReference Include="BepInEx.Core" Version="5.4.21" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
		<PackageReference Include="UnityEngine.Modules" Version="2022.3.29" />

      <PackageReference Include="Krafs.Publicizer" Version="2.3.0">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>

		<!-- Ultrakill DLL'S -->

		<Reference Include="plog">
			<HintPath>$(ManagedPath)\plog.dll</HintPath>
		</Reference>
		
		<!-- Managed -->
		<Reference Include="Assembly-CSharp :3">
			<HintPath>$(ManagedPath)\Unity.TextMeshPro.dll</HintPath>
		</Reference>
		<Reference Include="UnityEngine.UI rawr">
			<HintPath>$(ManagedPath)\UnityEngine.UI.dll</HintPath>
		</Reference>
		<Reference Include="Unity.AI.Navigation uwu">
			<HintPath>$(ManagedPath)\Unity.AI.Navigation.dll</HintPath>
		</Reference>
		<Reference Include="Facepunch.Steamworks.Win64 &gt;:3">
			<HintPath>$(ManagedPath)\Facepunch.Steamworks.Win64.dll</HintPath>
		</Reference>
		<Reference Include="Unity.Addressables [imagine a silly goober textmoji here]">
			<HintPath>$(ManagedPath)\Unity.Addressables.dll</HintPath>
		</Reference>
		<Reference Include="Unity.ResourceManager OwO">
			<HintPath>$(ManagedPath)\Unity.ResourceManager.dll</HintPath>
		</Reference>

		<!-- i dontr fucking care anymore STOP MAKING ME MAKE NUGET PACKAGES-->
    <Reference Include="lib/Unity.Addressables.dll" />
    <Reference Include="lib/UnityEngine.AssetBundleModule.dll" />
    <Reference Include="lib/Unity.ResourceManager.dll" />

    <PackageReference Include="bitmotte.com.ULTRAKILL.Assemblies" Version="17.1.1" />
    <PackageReference Include="bitmotte.com.Unity.TextMeshPro" Version="2022.3.29" />

      <Publicize Include="Assembly-CSharp" />
	</ItemGroup>

	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<Message Text="Copying DLL to: $(CopyPath)..." Importance="high" />
		<Copy SourceFiles="$(TargetPath)" DestinationFolder="$(CopyPath)" OverwriteReadOnlyFiles="true" />
	</Target>

</Project>
